# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181113_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='user',
            name='manager_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Processed'), (3, 'HR reviewed')], default=1),
        ),
    ]
