# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-13 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181113_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hr_approved_by',
            new_name='hr_reviewed_by',
        ),
    ]
