# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-14 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181113_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by_role', models.IntegerField(blank=True, choices=[(1, 'HR'), (2, 'MANAGER'), (3, 'REGULAR')], null=True)),
                ('reviewed_on_role', models.IntegerField(blank=True, choices=[(1, 'HR'), (2, 'MANAGER'), (3, 'REGULAR')], null=True)),
                ('review_type', models.IntegerField(blank=True, choices=[(1, 'HR'), (2, 'MANAGER'), (3, 'REGULAR')], null=True)),
                ('changed_from', models.CharField(max_length=50)),
                ('changed_to', models.CharField(max_length=50)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to=settings.AUTH_USER_MODEL)),
                ('reviewed_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_on', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
